id: PBD202F4D
initial_creation_type: input
source_metadata:
  Title: Seven Works of Vasubandhu
  Editor: Anacker, Stephan
  Publisher: Motilal Banarsidass
  Place of Publication: Delhi
  Year: '1984'
  Triṃśikāvijñaptikārikāḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:56:50.922135'
last_modified_at: '2022-03-08T16:56:50.922143'
